Romeu_Project/Models/CSharp/AccessModifiers.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Romeu_Project.Models.CSharp
{
    public class AccessModifiers
    {
    }
}

Romeu_Project/Models/CSharp/CSharp6/Static6.cs
using System;
using static System.Console;


namespace Romeu_Project.Models.CSharp.CSharp6
{
    public static class Static6
    {
        
        public static void FirstStaticMethod()
        {
            // C# 5 below Statics
            Console.WriteLine("Text");

            // # 6 Statics - devido ao using static System.Console
            WriteLine();


            // String interpolation
            string first = "Eu ";
            string scnd = "Voce  ";
            // C# 5
            Console.WriteLine("{0} quero, {1} quer", first, scnd);

            // C# 6
            WriteLine($"{first} quero, {1} quer");



        }
    }
}

Romeu_Project/Models/CSharp/FirstClass.cs
using System;

namespace Romeu_Project.Models.CSharp
{
    public class FirstClass
    {
        public string Value;

        private string _value;

        private string cor;
        public string Cor { get => cor; set => cor = value; }

        // Properties
        public string MainValue{
            get => MainValue;
            set => MainValue = value;
        }

        public FirstClass(){}

    }
}

Romeu_Project/Models/CSharp/MyInterface.cs
using System;
using Romeu_Project.Models.Interface;

namespace Romeu_Project.Models.CSharp
{
    // Interfaces são bem mais simples do que classes. Elas não tem atributos e seus métodos não tem implementação.
    // A interface apenas nos garante que o método existirá naquela classe. 
    // Por esse motivo, apesar de C# não suportar herança múltipla (ser filho de mais de uma classe), 
    // podemos implementar quantas interfaces quisermos. Basta colocar uma na frente da outra
    public class MyInterface : IInterface
    {
        private double amount;

        private string str;

        public MyInterface()
        {
            amount = 10;
            str = "Romeuuu";
        }

        public double GetValue()
        {
            return amount;
        }

        public void ShowValue()
        {
            Console.WriteLine($"Meu nome é {str}");
        }
    }

    public class MyInterface2 : IInterface
    {


        public double GetValue()
        {
            throw new NotImplementedException();
        }

        public void ShowValue()
        {
            throw new NotImplementedException();
        }
    }
}

Romeu_Project/Models/Interface/IInterface.cs
namespace Romeu_Project.Models.Interface
{
    public interface IInterface
    {
        void ShowValue();

        double GetValue();

    }
}

Romeu_Project/Models/MyData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Romeu_Project.Models
{
    public class MyData
    {
        public int MyId { get; set; }

        public string MyValue { get; set; }
    }
}

Romeu_Project/ViewModels/FirstViewViewModel.cs
using Romeu_Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Romeu_Project.ViewModels
{
    public class FirstViewViewModel
    {
        public IEnumerable<MyData> MyType { get; set; }
    }
}

Romeu_Project/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Romeu_Project.ViewModels
{
    public class LoginViewModel
    {
        // Forma de tornar required tal campo no site, passando a mensagem de erro em aspas
        [Required(ErrorMessage ="Username is required")] 
        [DataType(DataType.Text)]
        public string Username { get; set; }

        [Required(ErrorMessage ="Password is required")]
        [DataType(DataType.Password)]
        // Forma de colocar uma max lenght para o campo password
        [StringLength(150, ErrorMessage ="Must be between 5 and 150 characters", MinimumLength = 5)]
        public string Password { get; set; }
    }
}

Romeu_Project/Controllers/LoggedInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Romeu_Project.Controllers
{
    public class LoggedInController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

Romeu_Project/Controllers/MainController.cs
using Microsoft.AspNetCore.Mvc;
using Romeu_Project.Models;
using Romeu_Project.Services;
using Romeu_Project.ViewModels;
using System.Collections.Generic;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Romeu_Project.Controllers
{
    // Com o parametro abaixo, para abrir a pagina eh necessario digitar /test/ na frente da url
    // [Route("Test")]
    //[Route("[Controller]")]
    public class MainController : Controller
    {
        private IMyInjectedService myService;

        public MainController(IMyInjectedService myService)
        {
            this.myService = myService;
        }

        //[Route("Main")]
        //[Route("[Action]")]
        // GET: /<controller>/
        public IActionResult Index()
        {
            //ViewBag.value = "My First MVC!!!";
            ViewBag.myobject = this.myService;
            return View();
        }

        public IActionResult FirstView()
        {
            //var model = new MyData { MyId = 2, MyValue = "My Value" };

            var model = new List<MyData> {
                new MyData { MyId = 1, MyValue = "My Value 1" },
                new MyData { MyId = 2, MyValue = "My Value 2" }
            };

            var viewmodel = new FirstViewViewModel();
            viewmodel.MyType = model;

            return View(viewmodel);
        }

        //[Route("First")]
        //[Route("[Action]")]
        // public string IdRoute()
        public ContentResult IdRoute()
        {
            return Content("Attribute Routing");
        }

        // Return Types
        //[Route("[Action]")]
        // public ObjectResult MyObject()
        public JsonResult MyObject()
        {
            var mymodel = new MyData { MyId = 1, MyValue = "My First Value!!!"  };

            return Json(mymodel);
        }

        public IActionResult Authenticate()
        {
            if (ModelState.IsValid)
            {
                // Mandamos para o actio name = Index e com o LoggedIn Controller
                return RedirectToAction("Index", "LoggedIn");
            }
            else
            {
                return RedirectToAction("Index", "Main");
            }
        }

    }
}

Romeu_Project/ViewComponents/FirstViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Romeu_Project.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Romeu_Project.ViewComponents
{
    public class FirstViewComponent : ViewComponent
    {
        private IMyInjectedService myService;

        public FirstViewComponent(IMyInjectedService service)
        {
            myService = service;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            // LEMBRAR DE EVOCAR TODOS OS VIEWS COMPONENTES DE maneira ASSINCRONA
            var myItem = await GetGuid();
            return View("Default", myItem);
        }

        private async Task<IMyInjectedService> GetGuid()
        {
            return await Task.FromResult(myService);
        }

    }
}

Romeu_Project/ViewComponents/LoginViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Romeu_Project.ViewComponents
{
    public class LoginViewComponent:ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

Romeu_Project/Views/Main/FirstView.cshtml
@*Com isso obtem-se a intellissense para os comadnos de mondel MyData*@
@*@model Romeu_Project.Models.MyData*@

 @*PAra quando existe a lista de elementos*@
@*@model IEnumerable<Romeu_Project.Models.MyData>*@
@*@model Romeu_Project.ViewModels.FirstViewViewModel*@

@*Para a lista de elementos*@
@foreach (var item in Model.MyType)
{
    <p>@item.MyId</p>
    <p>@item.MyValue</p>
}

@*<p>@Model.MyId</p>
<p>@Model.MyValue</p>*@

Romeu_Project/Views/Main/Index.cshtml
@{
    ViewBag.Title = "My Title";
    // Se nao quisermos utilizar o Layout basico do _ViewStart apenas setar como null
    //Layout = null;
}

@await Component.InvokeAsync("Login")

@section header{
    <p> @ViewBag.myobject.MyGuid </p>
}

<h3> My Value</h3>

Romeu_Project/Views/PartialViews/FirstPartialView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>My First Partial View</h1>

<p> This is my View</p>

Romeu_Project/Views/Shared/Components/First/Default.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


@model Romeu_Project.Services.IMyInjectedService

<section>
    <h1>My First View Component</h1>
    <p>@Model.MyGuid</p>

</section>

Romeu_Project/Views/Shared/Components/Login/Default.cshtml
@model LoginViewModel 

@{
}


<div class="ui raised very padded text container" style="margin-right:5%;">

    <h3 class="ui header centered">APP LOGIN FORM</h3>

    <form asp-controller="Main" asp-action="Authenticate" method="post" class="ui large form validate-me" role="form"/>

    <div class="ui stack segment">
        <div class="field">
            <div class="ui left icon input">
                <i class="user icon"></i>
                <input asp-for="Username" placeholder="Username "/>
                <div asp-validation-for="Username" style="color:red;"></div>
            </div>
        </div>

        <div class="field">
            <div class="ui left icon input">
                <i class="lock icon"></i>
                <input asp-for="Password" placeholder="Password" />
                <div asp-validation-for="Password" style="color:red;"></div>
            </div>
        </div>

        <div>
            <button class="ui blue button">
                <i class="lock icon"></i>
                LOGIN
            </button>
        </div>

        <div asp-validation-summary="All" class="ui error" style="color:red;"></div>
    </div>


</div>

Romeu_Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @*<title>@ViewBag.Title</title>*@
    <title>@ViewData["Title"] - Romeu Project</title>

    <environment names="Development">
        <link href="~/lib/semantic/dist/semantic.min.css" rel="stylesheet" />
        <link href="~/css/site.css" rel="stylesheet" />
    </environment>

    <environment names="Staging.Production">
        <link href="~/lib/semantic/dist/semantic.min.css" rel="stylesheet" />
        <link href="~/css/site.css" rel="stylesheet" />
    </environment>
    @*@Html.ApplicationInsightsJavaScript(TelemetryConfiguration)*@
    @Html.Raw(snippet.FullScript)

</head>
<body>
    <div>
        @RenderBody()
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/semantic/dist/semantic.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/js/site.js"></script>
    </environment>

    <environment names="Staging.Production">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/semantic/dist/semantic.min.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
        <script src="~/js/site.js"></script>
    </environment>

    <header>
        @*Nome da sessao (para relacionar nas paginas que chamam o layout) e se eh required ou nao*@
        @RenderSection("header", false)
    </header>

    <div>
        @RenderBody()
    </div>

    @RenderSection("scripts", false)

    <footer>
        @*<p>My Footer</p>
        @await Component.InvokeAsync("First")*@
    </footer>
</body>
</html>

Romeu_Project/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @*<title>@ViewBag.Title</title>*@
    <title>@ViewData["Title"] - Romeu Project</title>

    <environment names="Development">
        <link href="~/lib/semantic/dist/semantic.min.css" rel="stylesheet" />
        <link href="~/css/site.css" rel="stylesheet" />
    </environment>

    <environment names="Staging.Production">
        <link href="~/lib/semantic/dist/semantic.min.css" rel="stylesheet" />
        <link href="~/css/site.css" rel="stylesheet" />
    </environment>
    @*@Html.ApplicationInsightsJavaScript(TelemetryConfiguration)*@
    @Html.Raw(snippet.FullScript)

</head>
<body>
    <div>
        @RenderBody()
    </div>


    @*<header>*@
        @*Nome da sessao (para relacionar nas paginas que chamam o layout) e se eh required ou nao*@
       @* @RenderSection("header", false)*@
    @*</header>*@

    <!-- SIDE BAR-->
    <div class="ui visible inverted left vertical sidebar menu">
        <a class="item"> <i class="home icon"></i> </a>
    </div>

    <!--Fixed NavBar-->
    <div class="ui top fixed menu">
        <a class="item" asp-controller="LoggedIn" asp-action="Logout">Logout</a>
    </div>

    <div>
        @RenderBody()
    </div>

    @RenderSection("scripts", false)

    <footer>
        @*<p>My Footer</p>
        @await Component.InvokeAsync("First")*@
    </footer>


    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/semantic/dist/semantic.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/js/site.js"></script>
    </environment>

    <environment names="Staging.Production">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/semantic/dist/semantic.min.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
        <script src="~/js/site.js"></script>
    </environment>
</body>
</html>